---
extends: "default"

rules:
    document-start:
        present: true
    braces:
        forbid: true
    brackets:
        forbid: false
    empty-values:
        forbid-in-block-mappings: false
        forbid-in-flow-mappings: true
    indentation:
        spaces: 2
        indent-sequences: true
    line-length: "disable"
    quoted-strings:
        quote-type: "double"
        required: false
