title: PrinsFrank.nl
email: prinsfrank@vuln.one
pgp_fingerprint: 058B EA0C 7B01 8E1E 1A07 7EED BC88 7FF5 7202 0508
description: >- # this means to ignore newlines until next key
 Web technology and application security taken seriously.<br>
 and other random thoughts
url: "https://prinsfrank.nl" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%Y-%m-%d"

linkedin_username: PrinsFrank
github_username: PrinsFrank
instagram_username: FranksGrandTour
thingiverse_username: PrinsFrank
polarsteps_username: PrinsFrank
google_scholar_username: oOZQKykAAAAJ
google_scholar_visible_name: Frank Prins

plant_uml_render_proxy: "https://www.plantuml.com/plantuml/proxy?src="
git_url: "https://raw.githubusercontent.com/PrinsFrank/PrinsFrank.nl/master/"
graphs_folder: "graphs/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-tidy

permalink: /:year/:month/:day/:title

show_drafts: false
defaults:
  -
    values:
      author: "Frank Prins"

build: 2021012202 # cache busting variable for css

visited_countries:
  - AT
  - BE
  - CH
  - CN
  - CZ
  - DE
  - ES
  - FR
  - GB
  - IL
  - IT
  - JO
  - JP
  - KH
  - KR
  - LI
  - LU
  - LV
  - MC
  - NL
  - PL
  - PS
  - SI
  - SK
  - SM
  - TR
  - UA
  - UZ
  - VA
  - VN
  - ZA
